/** @type {import('next').NextConfig} */
const nextConfig = {
  // Enable React Strict Mode for improved error handling and warnings in development.
  reactStrictMode: true,

  // Use SWC minification for faster builds and better performance.
  swcMinify: true,

  // Configure image optimization for Next.js Image component.
  images: {
    // Define allowed domains for external images.
    // This is crucial for security and performance when fetching images from CDNs or other services.
    // Example: If project screenshots or avatars are hosted on GitHub, a CDN, or a dedicated image service.
    domains: [
      'res.cloudinary.com', // Example: If using Cloudinary for image hosting
      'avatars.githubusercontent.com', // Example: For GitHub profile pictures
      'img.shields.io', // For badges in README or on the site
      // Add domains for other microservices if they serve images, e.g.,
      // process.env.MARKDOWN_PREVIEWER_IMAGE_DOMAIN, // If Markdown Previewer hosts images
      // process.env.TODO_APP_IMAGE_DOMAIN, // If Todo App hosts images
    ],
    // Define device sizes for responsive image generation.
    deviceSizes: [640, 750, 828, 1080, 1200, 1920, 2048, 3840],
    // Define image sizes for `srcSet` generation.
    imageSizes: [16, 32, 48, 64, 96, 128, 256, 384],
  },

  // Environment variables that are exposed to the client-side.
  // These are prefixed with NEXT_PUBLIC_ by convention for client-side exposure.
  // For sensitive variables, use .env.local without NEXT_PUBLIC_ and access them only on the server.
  env: {
    // API endpoint for the portfolio's own backend (if any, e.g., for contact form submissions or dynamic content).
    NEXT_PUBLIC_PORTFOLIO_API_URL: process.env.NEXT_PUBLIC_PORTFOLIO_API_URL || 'http://localhost:3001/api/portfolio',

    // API endpoint for the Markdown Previewer microservice.
    // This allows the portfolio to potentially embed or link to content generated by the Markdown Previewer.
    NEXT_PUBLIC_MARKDOWN_PREVIEWER_API_URL: process.env.NEXT_PUBLIC_MARKDOWN_PREVIEWER_API_URL || 'http://localhost:3002/api/markdown',

    // API endpoint for the Todo App microservice.
    // This could be used to display a user's todo list or integrate features from the Todo App.
    NEXT_PUBLIC_TODO_APP_API_URL: process.env.NEXT_PUBLIC_TODO_APP_API_URL || 'http://localhost:3003/api/todos',

    // Example for a shared authentication service URL
    NEXT_PUBLIC_AUTH_SERVICE_URL: process.env.NEXT_PUBLIC_AUTH_SERVICE_URL || 'http://localhost:3004/api/auth',
  },

  // Compiler options for SWC.
  compiler: {
    // Remove console.log statements in production builds for cleaner output and potentially smaller bundle sizes.
    // This helps prevent accidental logging of sensitive information in production.
    removeConsole: process.env.NODE_ENV === 'production',
    // If using styled-components, uncomment the following line:
    // styledComponents: true,
  },

  // Custom webpack configuration (optional).
  // Use with caution, as it can override Next.js's default optimizations.
  // webpack: (config, { isServer }) => {
  //   // Example: Add a custom loader or plugin
  //   // if (!isServer) {
  //   //   config.plugins.push(new MyCustomPlugin());
  //   // }
  //   return config;
  // },
};

module.exports = nextConfig;